# base image
FROM node:16.3.0-alpine

# set working directory
WORKDIR /app

# copy source files
COPY ../../ .

# install dependencies
RUN yarn

# expose port 3005
EXPOSE 3000

#CMD ["yarn", "dev", "--port", "3000"]
