version: '3.8'
services:
  app:
    build:
        context: .
        dockerfile: docker/nextjs/Dockerfile.dev
    ports:
     - "3000:3000"
    tty:
      true
    volumes:
        - .:/app

  nginx:
    container_name: server
    build:
        context: .
        dockerfile: docker/nginx/Dockerfile
    ports:
      - "8081:443"
    tty:
        true
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/ssl.conf

    depends_on:
      - app


