# base image
FROM node:16.3.0-alpine

# set working directory
WORKDIR /app

# copy source files
COPY ../../ .

# install dependencies
RUN yarn

#RUN yarn install

# expose port 3005
EXPOSE 3005

# start the app in development mode
#CMD ["yarn", "dev", "--port", "3005"]
